[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
watchPatterns = ["frontend/**"]

[environments.production.variables]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://${{backend.RAILWAY_PUBLIC_DOMAIN}}"

[environments.development.variables]
NODE_ENV = "development"
NEXT_PUBLIC_API_URL = "http://localhost:8000" 